### PR TITLE
Fixing es5 react compilation

### LINKED ISSUE #2: Should render es5 component (no babelified .default)
Error: Cannot find module 'react/lib/ReactDOMServer'

Any ideas?

### PR DESCRIPTION
**Pull request by dijs**
- Fixed README
- Added build task
- Fixed tests to work without babel-node
- ES5 React now compiles
- Fixes #2

### CODE REVIEW

**Comment by MoOx** [comment]
Thanks for this.
Why did you switch test to run on compiled files?
Can you update your commit message to something more relevant like "Fixed: support for es5 React component"?

**Comment by dijs** [comment]
Sure. I had to switch the tests because `npm test` would not compile otherwise. I guess you have babel-node as your default. I am betting many developers will not, so by compiling and running the tests everyone can clone/test/contribute with any node environment.

**Comment by dijs** [comment]
Commit message updated

**Comment by MoOx** [comment]
No I don't use babel-node by default.
Note that test don't use node or babel-node, but ava https://github.com/MoOx/metalsmith-react/blob/master/package.json#L38 which handle es6 (and the babel transformation https://github.com/MoOx/metalsmith-react/blob/master/package.json#L56).
Please revert this change, then I will be able merge and publish. Thank you!

**Comment by dijs** [comment]
I will revert the change. I am just letting you know that your project will not compile. 

All I did was `clone`, `npm install`, and `npm test`. And your project error'ed out.

**Comment by MoOx** [comment]
How do you explain that the CI works? Because that Travis does: clone, install & test.

**Comment by dijs** [comment]
My bad. I updated my node version to the latest stalble (5.4.1) and the tests started working.

Thanks for your help. Pull request should be ready now.

**Comment by MoOx** [comment]
Thank you!

**Comment by MoOx** [comment]
Released as 2.0.1.

**Pull request merged**
